### PR TITLE
New synch rad implementation + unittests

### PR DESCRIPTION
**Pull request by kiliakis**
- The new versions (boost and std) are scalable with more cores
- Slightly improved single thread performance
- Added few unittests, python vs cpp

### CODE REVIEW

**Comment by MarkusSchwarz1980** [comment]
@kiliakis 
- In all unit tests of type '_with_quant_exc', the Python functions have `quantum_excitation=False`, while SR_cpp have `quantum_excitation=True`. Shouldn't it read `quantum_excitation=True` for the Python functions as well? Because as is, the functions test two different physics scenarios. Maybe that's why `rtol_std = 1e-1` is very coarse in these function?
- In line 47 of synchrotron_radiation.cpp: The current line reads `beam_dE[i] = beam_dE[i] - const_synch_rad * beam_dE[i] - U0;` Naively, wouldn't it be faster to factor out the `beam_dE[i]`, i.e. `beam_dE[i] = (1 - const_synch_rad) * beam_dE[i] - U0;`?

**Comment by kiliakis** [comment]
@MarkusSchwarz1980 good points, let me have a look and update the pull request :)

**Comment by MarkusSchwarz1980** [comment]
@kiliakis 
I am still surprised that the unittests with quantum excitations only agree on the percent level. <strike>When I run Example 13 with either `python=True` or `False` I get the same number for `np.std(beam.dt)` (and `np.std(beam.dE)`) (using the version on the master branch)</strike>
edit: My fault, I checked after the first part of the example, where there is no quantum excitation

**Comment by kiliakis** [comment]
@MarkusSchwarz1980 Hmm, okay I will have a further look, perhaps there is some bug.

**Pull request merged**
